### ISSUE TITLE
Additional System Points of Interest

### ISSUE THREAD

**Issue by svmnotn** [mpigsley/sectors-without-number#46]
The ReadMe already says that adding star sizes is a possible feature, how about also randomly generating other planets that are not colonized purely for description purposes?

That would mean increasing the likelihood of more than 1 planet being generated in the system, but also allowing planets that have no world tags (which is already possible, however it looks weird as the "World Tags" section is still displayed), no population, and no tech level. However that would mean that the generator needs to make sure that planets either have no pop/tech/tags or they have at least one of each, it also means the generator needs to check that at least one planet in the system has pop/tech/tags at least while generating a system. These planets would make more use of #37, as the whole idea behind them is largely up to the GM.

On the same topic of more flavor, I'm not sure if 1st edition had this as I have not fully read the 1st edition, but for the revised edition, under Creating Stellar Sectors there is also a table on additional points of interest in a system. 

I think it would be interesting to allow the generator to cope with something like a deep space research station orbiting a black hole, it would be even better if it could randomly generate it.
This would require the generator being able to create non-planet objects in a system. These objects could be as simple as a name and a text box, or you could use the table to fill in some possibilities. I think this is covered under the idea of adding asteroid fields, but there can be so much more than asteroids in a system that I think it deserved a more general name.

**Comment by mpigsley** [comment]
Hey @svmnotn! Sorry, I can't believe I'm just now seeing this.

So here's what I'm thinking going forward. The first level will be all the objects you can place at any hex in the sector. 

* `System`
  * `Planet`
    * `Moon`
      * `Research Station`
      * `Refueling Station`
      * `Moon Base`
    * `Orbital Ruin`
    * `Research Station`
    * `Refueling Station`
  * `Blank/Other World`
  * `Gas Giant Mine`
  * `Refueling Station`
  * `Space Station`
  * `Research Station`
* `Deep Space Station`
* `Asteroid Field/Belt`
  * `Asteroid Base`
  * `Refueling Station`
  * `Research Station`
* `Black Hole`
  * `Deep Space Station`
  * `Refueling Station`
  * `Research Station`
  * `Orbital Ruin`

Every entity will have the ability to contain a randomized adventure or faction.

The ability to nest entities in the UI as well a see a single list of a specific type of entity (e.g. all factions, asteroid bases, etc. etc.) is what I'm currently thinking through at the moment.

**Comment by svmnotn** [comment]
That sound great!

**Comment by mpigsley** [comment]
This updated sidebar design will resolve...

* Additional Points of Interest
* Player & GM Views (https://github.com/mpigsley/sectors-without-number/issues/46)
* Notes (https://github.com/mpigsley/sectors-without-number/issues/37)
* Custom Planet Tag Data (https://github.com/mpigsley/sectors-without-number/issues/66)

![Updated Sidebar](https://user-images.githubusercontent.com/3017491/32917200-0c15c620-cae4-11e7-9d01-c4c791763394.jpeg)

### Roadmap:

* [ ] Ability to go into edit mode in the sidebar instead of pulling up an edit modal
* [ ] Ability to add custom planet tag data (https://github.com/mpigsley/sectors-without-number/issues/66)
* [ ] Ability to hide entities and attributes from players (https://github.com/mpigsley/sectors-without-number/issues/46)
* [ ] Additional Points of Interest
  * [ ] Build the static relationships between entities [outlined in the previous comment](https://github.com/mpigsley/sectors-without-number/issues/46#issuecomment-338437637)
  * [ ] Decide how to store the data
  * [ ] Rework routes since deep routing is going to be pushing the limit of what browsers allow
  * [ ] Build additional points of interest into the sidebar with ability to go into edit mode
  * [ ] Build entity list toggles in the sidebar

Notes will follow additional points of interest.
